VERSION 0.6
FROM python:3
WORKDIR /code

build:
     # In Python, there's nothing to build.
    COPY src src
    SAVE ARTIFACT src /src AS LOCAL ./src-copy

docker:
    FROM +build
    ENTRYPOINT ["python3", "./src/hello.py"]
    SAVE IMAGE python-example:latest
 